"""Public immutable model contracts available through stage 13."""

from math_drawing_assistant.models.diagnostics import StageTiming
from math_drawing_assistant.models.errors import ErrorCode, ErrorInfo, SourceSpan
from math_drawing_assistant.models.plot_specs import (
    AxisOrientation,
    CircleSpec,
    EllipseSpec,
    EquationProvenance,
    ExplicitFunctionSpec,
    ExplicitExpressionSource,
    HyperbolaSpec,
    LineSpec,
    ParabolaOpening,
    ParabolaSpec,
    PlotItemSpec,
    PlotSceneSpec,
    PrimitiveEquationCoefficients,
    ValidatedExplicitExpression,
)
from math_drawing_assistant.models.restricted_ast import (
    BinaryOpNode,
    BinaryOperator,
    ConstantName,
    ConstantNode,
    FunctionCallNode,
    FunctionName,
    NumberNode,
    RestrictedExpression,
    SourceLocatedNode,
    SymbolNode,
    UnaryOpNode,
    UnaryOperator,
    VariableName,
)
from math_drawing_assistant.models.render_plan import (
    AngularSamplingPolicy,
    DEFAULT_ANGULAR_SAMPLING_POLICY,
    DEFAULT_EXPLICIT_SAMPLING_POLICY,
    DEFAULT_LINE_SAMPLING_POLICY,
    RENDER_PLAN_CONTRACT_VERSION,
    ExplicitRenderItemPlan,
    ExplicitSamplingPolicy,
    GeometryRenderItemPlan,
    GeometrySegmentPlan,
    LineSegmentPlan,
    LineSamplingPolicy,
    PARAMETERIZED_SAMPLER_CONTRACT_VERSION,
    ParameterIntervalPlan,
    ParameterizedRenderMemoryBudget,
    RenderItemPlan,
    RenderMemoryBudget,
    RenderPlan,
    SegmentClosure,
    validate_approved_render_plan,
)
from math_drawing_assistant.models.requests import PlotItemRequest, PlotSceneRequest
from math_drawing_assistant.models.results import PlotItemResult, PlotSceneResult
from math_drawing_assistant.models.state import (
    AspectRequest,
    InputSource,
    PlotKind,
    ResolvedAspect,
    TaskPhase,
    ViewportMode,
    ViewportSource,
)
from math_drawing_assistant.models.viewport import ResolvedViewport, ViewportRequest

__all__ = [
    "AngularSamplingPolicy",
    "AspectRequest",
    "AxisOrientation",
    "CircleSpec",
    "EllipseSpec",
    "ErrorCode",
    "ErrorInfo",
    "EquationProvenance",
    "ExplicitFunctionSpec",
    "ExplicitExpressionSource",
    "ExplicitRenderItemPlan",
    "ExplicitSamplingPolicy",
    "LineSamplingPolicy",
    "GeometryRenderItemPlan",
    "GeometrySegmentPlan",
    "BinaryOpNode",
    "BinaryOperator",
    "ConstantName",
    "ConstantNode",
    "FunctionCallNode",
    "FunctionName",
    "InputSource",
    "HyperbolaSpec",
    "LineSpec",
    "LineSegmentPlan",
    "ParabolaOpening",
    "ParabolaSpec",
    "PlotItemRequest",
    "PlotItemResult",
    "PlotItemSpec",
    "PlotKind",
    "PlotSceneRequest",
    "PlotSceneResult",
    "PlotSceneSpec",
    "PrimitiveEquationCoefficients",
    "PARAMETERIZED_SAMPLER_CONTRACT_VERSION",
    "ParameterIntervalPlan",
    "ParameterizedRenderMemoryBudget",
    "NumberNode",
    "DEFAULT_ANGULAR_SAMPLING_POLICY",
    "DEFAULT_EXPLICIT_SAMPLING_POLICY",
    "DEFAULT_LINE_SAMPLING_POLICY",
    "RENDER_PLAN_CONTRACT_VERSION",
    "RenderMemoryBudget",
    "RenderItemPlan",
    "RenderPlan",
    "RestrictedExpression",
    "ResolvedViewport",
    "ResolvedAspect",
    "SegmentClosure",
    "SourceSpan",
    "StageTiming",
    "SourceLocatedNode",
    "SymbolNode",
    "TaskPhase",
    "ViewportMode",
    "ViewportRequest",
    "ViewportSource",
    "UnaryOpNode",
    "UnaryOperator",
    "ValidatedExplicitExpression",
    "validate_approved_render_plan",
    "VariableName",
]
